name: Build and Release App

on:
  push:
    branches: [ "alpha" ]
    tags: [ "v*" ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    strategy:
      matrix:
        os:
          - name: windows-x64
            runner: windows-latest
            build-command: ./gradlew packageExe
            artifact-path: build/compose/binaries/main/exe/*.exe
          - name: windows-arm64
            runner: windows-latest-arm64
            build-command: ./gradlew packageExe
            artifact-path: build/compose/binaries/main/exe/*.exe
          - name: macos
            runner: macos-latest
            build-command: ./gradlew packageUberJarForCurrentOS
            artifact-path: build/compose/jars/materia-launcher.jar
          - name: linux-x64
            runner: ubuntu-latest
            build-command: ./gradlew packageUberJarForCurrentOS
            artifact-path: build/compose/jars/materia-launcher.jar

    runs-on: ${{ matrix.os.runner }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Java 25
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '25'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Build the application
        run: ${{ matrix.os.build-command }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os.name }}-artifact
          path: ${{ matrix.os.artifact-path }}
          if-no-files-found: error

  release:
    needs: [build]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: ./artifacts/**/*
          generate_release_notes: true
          draft: true
