name: Dev Build

on:
  workflow_dispatch:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install WiX Toolset v3.11 and add to PATH
        shell: pwsh
        run: |
          # Скачиваем и устанавливаем WiX v3.11
          $wixUrl = "https://github.com/wixtoolset/wix3/releases/download/wix3112rtm/wix311.exe"
          $wixExe = "wix311.exe"
          Invoke-WebRequest -Uri $wixUrl -OutFile $wixExe
          Start-Process -FilePath ".\\$wixExe" -ArgumentList "/install", "/quiet", "/norestart" -Wait
          
          # Принудительно добавляем WiX в PATH
          $wixBinPath = "C:\\Program Files (x86)\\WiX Toolset v3.11\\bin"
          echo "Adding $wixBinPath to PATH"
          echo "$wixBinPath" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - name: Set up Zulu JDK
        uses: actions/setup-java@v4
        with:
          java-version: '25'
          distribution: 'zulu'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Build with Gradle
        run: ./gradlew createDistributable

      - name: Archive distributable
        run: |
          Compress-Archive -Path build/compose/binaries/main/dist -DestinationPath materia-launcher-dev.zip
        shell: pwsh

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: materia-launcher-dev-windows
          path: materia-launcher-dev.zip
